project_name: mks
builds:
  - binary: mks
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - openbsd
      - plan9
      - windows
    goarch:
      - arm
      - arm64
      - amd64
      - 386
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: linux
        goarch: arm
        goarm: 7
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
