name: CI
on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.18

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46

      - name: Build
        run: go build

      - name: Test
        run: make test
