name: CI
on:
  push:
    branches:
      - 'master'
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: 1.18

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.46

      - name: Build
        run: go build

      - name: Test
        run: make test

  dependabot_automerge:
    name: Dependabot auto-merge
    runs-on: ubuntu-latest
    needs: [ test ]
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.metadata.outputs.dependency-names == 'actions/checkout' || steps.metadata.outputs.dependency-names == 'actions/setup-go' || steps.metadata.outputs.dependency-names == 'golangci/golangci-lint-action' || steps.metadata.outputs.dependency-names == 'dependabot/fetch-metadata' || steps.metadata.outputs.dependency-names == 'goreleaser/goreleaser-action' }}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
