name: CI
on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2.1.2
        with:
          go-version: 1.14

      - name: Format
        run: go fmt

      - name: Build
        run: go build
